name: Deploy Azure Data Platform

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        run: |
          az deployment group create \
            --resource-group rg-sales-platform-dev \
            --template-file infra/bicep/main.bicep \
            --parameters @infra/bicep/parameters/dev.json
